### ISSUE TITLE
server w/Epoll Exceptions

### ISSUE THREAD

**Issue by CRHough** [pyr/net#15]
Using Epoll on the server initially throws for a protocol problem. Once that's fixed (PR #16) I get

```Java
io.netty.channel.AbstractChannel$AbstractUnsafe closeForcibly
WARNING: Failed to close a channel.
java.lang.IllegalStateException: channel not registered to an event loop
	at io.netty.channel.AbstractChannel.eventLoop(AbstractChannel.java:158)
	at io.netty.channel.epoll.AbstractEpollChannel.doDeregister(AbstractEpollChannel.java:134)
	at io.netty.channel.epoll.AbstractEpollChannel.doClose(AbstractEpollChannel.java:111)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.closeForcibly(AbstractChannel.java:703)
	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:337)
	at io.netty.bootstrap.AbstractBootstrap.doBind(AbstractBootstrap.java:283)
	at io.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:279)
	at io.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:261)
	at net.ty.bootstrap$bind_BANG_.invokeStatic(bootstrap.clj:125)
	at net.ty.bootstrap$bind_BANG_.invoke(bootstrap.clj:122)
	at net.tcp$server.invokeStatic(tcp.clj:21)
	at net.tcp$server.invoke(tcp.clj:16)
```

Here's my server call (which worked with some patches, merged in beta4, before the protocols)
```Clojure
(tcp/server {:handler (pipeline)
                    :group (EpollEventLoopGroup.)
                    :channel EpollServerSocketChannel}
                    "localhost" 50000)
```

Everything works fine without Epoll.

**Comment by pyr** [comment]
Everything is now functional with epoll. Cheers!
